version: '2.3'

services:
  zerotier-route-server:
    image: jpvoss/zerotier-bird-router
    container_name: zerotier-bird-router
    restart: unless-stopped
    volumes:
      - zerotier_conf:/var/lib/zerotier-one
      - bird_conf:/opt/bird/etc
