version: '2.3'

services:
  zerotier-route-server:
    image: jvoss/zerotier-route-server
    container_name: zerotier-route-server
    restart: unless-stopped
    volumes:
      - zerotier_conf:/var/lib/zerotier-one
      - bird_conf:/opt/bird/etc
